name: Running Sync

on:
  workflow_dispatch:
    inputs:
      activity_id:
        required: false
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Print trigger data
        run: |
          echo "Triggered from Strava"
          echo "Activity ID: ${{ github.event.inputs.activity_id }}"
          date